[package]
name = "acttey"
description = "A simple graphics palette for more interactive web page"
repository = "https://github.com/ecoricemon/acttey"
license = "Apache-2.0 OR MIT"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
lto = true

[dependencies]
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
bytemuck = { version = "1.13.1", features = [
    "derive",
    "min_const_generics"
]}
paste = "1.0.14"
js-sys = "0.3.64"
wgpu = "0.18.0"
web-sys = { version = "0.3.64", features = [
    "console",
    "Window",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "MouseEvent"
]}
winit = "0.29.1-beta"
erased-generic-trait = "0.0.4"
acttey-ecs-macros = { path = "src/ecs/macros" }
console_error_panic_hook = "0.1.7"
uuid = { version = "1.5.0", features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
    "js"                 # For WebAssembly
]}
ahash = "0.8.6"

[dev-dependencies]
wasm-bindgen-test = "0.3.37"

# Just let rust-analyzer know, so that it will look for examples and show us something like inlay hints.
[[example]]
name = "basic"
path = "examples/basic/src/lib.rs"
crate-type = ["cdylib", "rlib"]
